config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :tasks
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :user_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light ms-3" href="<%= root_path%>">Task Manager  </a>
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %> 
          <div class="nav-item dropdown ">
            <a class="nav-link text-light dropdown-toggle me-3" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email%>
              <%# <%= link_to "Create New Order", new_order_path, class: "btn btn-primary" %> 

            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit Profile ', edit_user_registration_path,class:"dropdown-item my-1 me-auto" %>
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Sign out", destroy_user_session_path, class: "dropdown-item  my-1 me-auto", method: :delete %> 
            </ul>
          </div>
        <%else%>
          <div class="d-flex"><%= link_to "Sign in", new_user_session_path, class:"nav-link active"  %><p class="mt-2">/</p>
          <%= link_to "Sign up", new_user_registration_path	, class:"nav-link active" %></div>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class = "container">
      <%= render "layouts/header" %>
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <% if current_user.present? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  <% end %>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.datetime_local_field :due_date, class: 'form-control' %>
  </div>

  <div class="actions mt-2">
    <%= form.submit 'Create Task', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>New Task</h1>

<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1 class="display-4 mb-4">Tasks</h1>

  <div class="row">
    <% @tasks.each do |task| %>
      <div class="col-md-4 mb-4">
        <a href="<%= task_path(task) %>" style="text-decoration: none; color: inherit;">
          <div class="card zoom" <% if task.due_date.present? && task.due_date < Time.now %><% end %>>
            <div class="card-body mx-auto">
              <h5 class="card-title"><%= task.title %></h5>
              <% if task.due_date.present? %>
                <span class="badge bg-dark rounded-pill"><%= task.due_date.strftime('%b %d, %Y, %H:%M:%S') %></span>
              <% else %>
                <span class="badge bg-secondary rounded-pill">No due date</span>
              <% end %>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <button id="add-task-button" class="btn btn-dark">Add New Task</button>
      <div id="new-task-form" style="display: none;">
        <%= render 'form', task: Task.new %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<!-- app/views/tasks/new.html.erb -->
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <%= render 'form', task: Task.new %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body text-center">
      <h2 class="card-title"><%= @task.title %></h2>
      <p class="card-text"><%= @task.description %></p>
      <% if @task.due_date.present? %>
      <span class="badge bg-dark rounded-pill"><%= @task.due_date.strftime('%b %d, %Y, %H:%M:%S') %></span>
      <% else %>
        <span class="badge bg-secondary rounded-pill">No due date</span>
      <% end %>
      <%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-warning" %>

      <%= link_to "Destroy", task_path(@task), class: "btn btn-danger", data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $(".card").each(function() {
      var dueDate = new Date($(this).find(".badge").text());
      if (dueDate < new Date()) {
        $(this).animate({
          opacity: 0.15
        });
      }
    });
  });
</script>